site_name: Blitz Documentation
site_description: Blitz Trading Platform API, SDK and Broker Integration Documentation
site_author: Blitz
site_url: https://your-domain.com

repo_name: Blitz
#repo_url: https://github.com/your-org/blitz-docs

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico

  features:
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - toc.follow
    - content.code.copy
    - search.highlight
    - search.suggest

  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji

extra_css:
  - css/custom.css

copyright: "Â© Blitz"

nav:
  - Introduction: index.md

  # ---------------------------------------------------
  # API REFERENCE
  # ---------------------------------------------------

  - API Reference:
      - Overview: api/overview.md
      - Authentication: api/authentication.md

      - Trading APIs:
          - Orders: api/trading/orders.md
          - Trades: api/trading/trades.md
          - Signals: api/trading/signal.md
          #- Positions: api/trading/positions.md

      - Market Data APIs:
          #- Last Trading Price: api/market-data/ltp.md
          - Option Chain: api/market-data/optionchain.md
          #- Market Quote: api/market-data/marketquote.md
          - Instruments: api/market-data/instrumentId.md
          #- Historical Data: api/market-data/historicaldata.md

  # ---------------------------------------------------
  # SDK
  # ---------------------------------------------------

  - Blitz SDK:
      - SDK: sdk/sdk.md

  # ---------------------------------------------------
  # TPOMS
  # ---------------------------------------------------

  - TPOMS:
      - Overview: tpoms/overview.md
      - Order Request: tpoms/blitz_order_request.md

      - Broker Integrations:
          - Zerodha: tpoms/brokers/zerodha.md
          - Motilal: tpoms/brokers/motilal.md
